/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import primitive.Tree;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import primitive.CoreNode;

/**
 *
 * @author Yan
 */
public class BTree extends javax.swing.JFrame {

  private Tree<Integer> three;
  private JToggleButton[] numberButtons;
  private static final int order = 4;

  /**
   * Creates new form Runner
   */
  public BTree() {
    three = new Tree<>(order);
    initComponents();
    setLocationRelativeTo(null);
    insertNumbers(77);
  }

  private void insertNumbers(int length) {
    numberButtons = new JToggleButton[length];
    DecimalFormat dc = new DecimalFormat("00");
    ArrayList<Integer> fulllist = new ArrayList<>();
    for (int x = 0; x < 100; x++) {
      fulllist.add(x);
    }
    Collections.shuffle(fulllist);
    ArrayList<Integer> list = new ArrayList<>();
    for (int x = 0; x < length; x++) {
      list.add(fulllist.remove(0));
    }
    Collections.sort(list);

    for (int x = 0; x < numberButtons.length; x++) {
      numberButtons[x] = new JToggleButton(dc.format(list.remove(0)));
      numberButtons[x].addActionListener(new ButtonListener(numberButtons[x]));
      numberPanel.add(numberButtons[x]);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    numberPanel = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    inputField = new javax.swing.JTextField();
    searchButton = new javax.swing.JButton();
    addButton = new javax.swing.JButton();
    removeButton = new javax.swing.JButton();
    orderLabel = new javax.swing.JLabel();
    orderBox = new javax.swing.JComboBox();
    jScrollPane1 = new javax.swing.JScrollPane();
    jPanel1 = three.getVisual();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    numberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Numeros Aleatórios"));
    numberPanel.setDoubleBuffered(false);
    numberPanel.setMaximumSize(new java.awt.Dimension(22, 33));

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Manual"));

    jPanel3.setLayout(new java.awt.GridBagLayout());

    inputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    inputField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    inputField.setPreferredSize(new java.awt.Dimension(6, 30));
    inputField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        inputFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel3.add(inputField, gridBagConstraints);

    searchButton.setText("buscar");
    searchButton.setMaximumSize(new java.awt.Dimension(73, 23));
    searchButton.setMinimumSize(new java.awt.Dimension(73, 23));
    searchButton.setPreferredSize(new java.awt.Dimension(73, 23));
    searchButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 10;
    jPanel3.add(searchButton, gridBagConstraints);

    addButton.setText("add");
    addButton.setMaximumSize(new java.awt.Dimension(73, 23));
    addButton.setMinimumSize(new java.awt.Dimension(73, 23));
    addButton.setPreferredSize(new java.awt.Dimension(73, 23));
    addButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 10;
    jPanel3.add(addButton, gridBagConstraints);

    removeButton.setText("remover");
    removeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        removeButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 10;
    jPanel3.add(removeButton, gridBagConstraints);

    orderLabel.setText("Ordem");

    orderBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4 ligações, 3 campos","5 ligações, 4 campos","6 ligações, 5 campos",
      "7 ligações, 6 campos","8 ligações, 7 campos","9 ligações, 8 campos"}));
orderBox.addActionListener(new java.awt.event.ActionListener() {
  public void actionPerformed(java.awt.event.ActionEvent evt) {
    orderBoxActionPerformed(evt);
  }
  });

  javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
  jPanel2.setLayout(jPanel2Layout);
  jPanel2Layout.setHorizontalGroup(
    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel2Layout.createSequentialGroup()
      .addContainerGap()
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addComponent(orderLabel)
          .addGap(18, 18, 18)
          .addComponent(orderBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
      .addContainerGap())
  );
  jPanel2Layout.setVerticalGroup(
    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel2Layout.createSequentialGroup()
      .addGap(21, 21, 21)
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(orderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(orderLabel))
      .addGap(18, 18, 18)
      .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
  jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
  jScrollPane1.setAutoscrolls(true);

  jPanel1.setBackground(new java.awt.Color(255, 255, 255));
  jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
  jPanel1.setForeground(new java.awt.Color(0, 0, 255));
  jPanel1.setMinimumSize(new java.awt.Dimension(698, 548));
  jPanel1.setPreferredSize(new java.awt.Dimension(698, 548));

  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
  jPanel1.setLayout(jPanel1Layout);
  jPanel1Layout.setHorizontalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 848, Short.MAX_VALUE)
  );
  jPanel1Layout.setVerticalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 544, Short.MAX_VALUE)
  );

  jScrollPane1.setViewportView(jPanel1);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
      .addContainerGap()
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(numberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
      .addContainerGap())
  );
  layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
      .addContainerGap()
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(numberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
      .addContainerGap())
  );

  pack();
  }// </editor-fold>//GEN-END:initComponents

  private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
//    try {
//      Integer num = Integer.parseInt(inputField.getText());
//      three.remove(num);
//    }
//    catch (NucleoNode.ValueNotFoundException ex) {
//      JOptionPane.showMessageDialog(rootPane, ex.getMessage());
//    }
  }//GEN-LAST:event_removeButtonActionPerformed

  private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_inputFieldActionPerformed

  private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
    Integer num = Integer.parseInt(inputField.getText());
    three.search(num);
  }//GEN-LAST:event_searchButtonActionPerformed

  private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    Integer num = Integer.parseInt(inputField.getText());
    three.add(num);
  }//GEN-LAST:event_addButtonActionPerformed

  private void orderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBoxActionPerformed
    int selectedOrder = orderBox.getSelectedIndex() + 4;

    if (three.getOrder() != selectedOrder) {
      three.setOrder(selectedOrder);
      numberPanel.removeAll();
      insertNumbers(77);
      numberPanel.repaint();
      numberPanel.revalidate();
    }

  }//GEN-LAST:event_orderBoxActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    }
    catch (Exception ex) {
      ex.printStackTrace();
    }
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new BTree().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addButton;
  private javax.swing.JTextField inputField;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel numberPanel;
  private javax.swing.JComboBox orderBox;
  private javax.swing.JLabel orderLabel;
  private javax.swing.JButton removeButton;
  private javax.swing.JButton searchButton;
  // End of variables declaration//GEN-END:variables

  private class ButtonListener implements ActionListener {

    private final JToggleButton button;

    public ButtonListener(JToggleButton button) {
      this.button = button;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
      if (!button.isSelected()) {

        try {
          Integer num = Integer.parseInt(button.getText());
          three.remove(num);
        }
        catch (CoreNode.ValueNotFoundException ex) {
          JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

      }
      else {

        Integer num = Integer.parseInt(button.getText());
        three.add(num);

      }
    }
  }
}
